services:
  - type: web
    name: bookhub
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: DATABASE_URL
        value: sqlite:////tmp/bookhub.db
    healthCheckPath: /api/books